[tool.poetry]
name = "poke-cli"
version = "0.1.0"
description = ""
authors = ["AB <a@b.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pymetasploit3 = "1.0.6"
mamba = "0.11.3"
expects = "0.9.0"
pysonar-scanner = "0.2.0.520"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
